### ISSUE TITLE
MIECD Dashboard Performance

### ISSUE THREAD

**Issue by hmakandi** [OpenSRP/opensrp-web#155]
- [ ] The dashboard is slow and has performance issues, we need to make it load the pages faster.

**Comment by FrankApiyo** [comment]
In order to load pages faster, I suggest using local storage for storing sms events, and checking by ID which sms events are already stored locally before attempting to fetch them. In addition we can make a check of which still exist in superset in order to remove the once that do not exist in superset. 

*cc* @moshthepitt, @HusnaHariz , @hmakandi

**Comment by moshthepitt** [comment]
Are there any very private things in these SMS events?

**Comment by HusnaHariz** [comment]
At the moment the dashboards are querying all the data from one slice. This requires alot of filtering on te frontend. This is contributing to slow performance. We had discussed with @hmakandi  that we will instead create separate slices for each chart/dashboard on the webapp.

**Comment by hmakandi** [comment]
Closing this with an aim of looking at this at a later stage.
